### ISSUE TITLE
webserver: pass commands to ansible and send output

### ISSUE THREAD

**Issue by sometheycallme** [cleanerbot/ansible-security#78]
@Jfach 

Now that we have a data model for the webserver to listen to clientside commands, we need to 

- send the command to ansible 

- take stdout / stderr from ansible after ```ansible-playbook``` and send it back to the user

**Comment by sometheycallme** [comment]
Here is a playboook I'm using in the circle CI tests that will always be in the repository to test with.

```json
curl -v -X POST -d '{"branch_name": "master", "git_handle": "cleanerbot", "flags": [{"flag": "-i", "argument": "inventory"}], "playbook": "/fixtures/etc/ansible/play-test.yml"}' http://${ip}:${port}/play
```

**Comment by sometheycallme** [comment]
This is needed for #40

**Comment by Jfach** [comment]
@sometheycallme 
The webserver is currently using `os.system` to run the ansible commands. If we want to do things with the output of the command, we will need to use `Popen` and `PIPES` like we did in autostager.

**Comment by sometheycallme** [comment]
#40 

@Jfach 

I tested this in #81 and documented the steps.

On the pipeline host in Digital ocean using the IP of the controller - no good.

We have a few other kinks to work out with ansible as well (read-only staging directory will likely not work for us, we'll need to mount rw)

**Comment by sometheycallme** [comment]
@Jfach 

When you have a moment, see if you can run the ansible-playbook (you can do this in the devenv container).  The output of the playbook is what we need to send to the client side.

**Comment by sometheycallme** [comment]
@Jfach 

I see this....

```python
    def local_sha(self):
        #print "======================"
        #print "      LOCAL SHA       "
        #print "======================"
        os.chdir(self.staging_dir)
        args = ["git", "log", "--pretty='%H'", "HEAD^1.."]
        cmd = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE)
        output, err = cmd.communicate()
        local_sha = output.decode('UTF-8').strip()[1:-1]
        return local_sha
```

http://stackoverflow.com/questions/21430245/python-redirect-stdout-to-a-socket

If I'm not mistaken, it seems like we'll need to redirect stdout from the cmd we send to ansible-> to socket and send back to the client.

**Comment by sometheycallme** [comment]
Actually, why bother, if BaseHTTPServer has some methods for us to 

```python
	    command += " {0}/{1}/{2}".format(base_dir, safe_dir, playbook) 
	    print command
	    os.system(command)
	    self.send_response(200)
	    return
```

with self.send_response we can send information back (it uses sockets)

http://stackoverflow.com/questions/12731207/how-can-i-debug-post-requests-with-pythons-basehttpserver-simplehttpserver

https://wiki.python.org/moin/BaseHttpServer

extra:

- some logging options with ansible

http://stackoverflow.com/questions/18794808/how-do-i-get-logs-details-of-ansible-playbook-module-executions

**Comment by sometheycallme** [comment]
Latest test results, running the curl command against the webserver

```
core@pipeline ~/ansible-security $ docker run --volumes-from staging-data:ro -p 8080:8080 -i -t ansible-controller bash
Listening on localhost:8080

{u'branch_name': u'master', u'git_handle': u'cleanerbot', u'flags': [{u'flag': u'-i', u'argument': u'inventory'}], u'playbook': u'/fixtures/etc/ansible/play_test.yml'}
[{u'flag': u'-i', u'argument': u'inventory'}]
{u'flag': u'-i', u'argument': u'inventory'}
----------------------------------------
Exception happened during processing of request from ('172.17.0.5', 58910)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "webserver/server.py", line 69, in do_POST
    path = os.path.join(base_dir, safe_dir)
UnboundLocalError: local variable 'base_dir' referenced before assignment
----------------------------------------
```

**Comment by sometheycallme** [comment]
@Jfach 

Getting close:  adding the following to server.py 

```proc = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)```

bigger snippet

```python
            command = "ansible-playbook"
            if flags:
                for flag in flags:
                    command += " {0}".format(flag['flag'])
                    if flag['argument']:
                        command += " {0}".format(flag['argument'])
            # base_dir: must add the env_var file with docker run --env-file /home/core/env_vars
            directory = post_data['git_handle'] + '/' + post_data['branch_name']
            base_dir = os.environ['base_dir']
            safe_dir = self.alphafy(directory)
            command += " {0}/{1}/{2}".format(base_dir, safe_dir, playbook)
            # Use this to set ANSIBLE_HOSTS environment variable as base_dir, safe_dir
            path = os.path.join(base_dir, safe_dir)
            os.chdir(path)
            os.putenv('ANSIBLE_HOSTS',path+'/'"hosts")
            proc = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
            (out, err) = proc.communicate()
            #logging
            #use os.system(command) in favor of subprocess
            print "program output:", out
            print (command)
            print path
            self.send_response(200)
            return  
```

yielded this:

```
----------------------------------------
{u'branch_name': u'webserver', u'git_handle': u'cleanerbot', u'flags': [{u'flag': u'-i', u'argument': u'hosts'}], u'playbook': u'/fixtures/etc/ansible/play_test.yml'}
[{u'flag': u'-i', u'argument': u'hosts'}]
{u'flag': u'-i', u'argument': u'hosts'}
/fixtures/etc/ansible/play_test.yml
program output: 
PLAY [local] *******************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Ansible Ping Localhost] **************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   


ansible-playbook -i hosts /opt/staging/cleanerbot_webserver//fixtures/etc/ansible/play_test.yml
/opt/staging/cleanerbot_webserver

172.17.0.1 - - [04/Jul/2016 14:44:26] "POST /play HTTP/1.1" 
PLAY [local] *******************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Ansible Ping Localhost] **************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
----------------------------------------
Exception happened during processing of request from ('172.17.0.1', 33896)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "webserver/server.py", line 90, in do_POST
    self.send_response(out)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 404, in send_response
    (self.protocol_version, code, message))
TypeError: %d format: a number is required, not str
----------------------------------------
```

The exception is from self.send_response(out).   Next is to try and pass stdout from ansible playbook to self.send_response()

**Comment by sometheycallme** [comment]
self.send_response() is expecting a number not a string.

```
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 404, in send_response
    (self.protocol_version, code, message))
TypeError: %d format: a number is required, not str
```

**Comment by sometheycallme** [comment]
send_response(self, code, message=None)

Send the response header and log the response code.

Also send two standard headers with the server software version and the current date.

**Comment by sometheycallme** [comment]
https://github.com/willthames/python-logging-proxy/blob/master/LoggingProxyHTTPHandler.py

**Comment by sometheycallme** [comment]
wonder if we can do this:

```self.respond(out)```

**Comment by sometheycallme** [comment]
need this

http://docs.python-requests.org/en/master/

**Comment by sometheycallme** [comment]
this commit here https://github.com/cleanerbot/ansible-security/pull/105/commits/39f9a6c299811d52fe386d08e8cae29fde4988dd  with linting provided proper syntax for sending output of the ansibe-playbook command.
